# Generated by Django 3.0.5 on 2020-04-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_program_program_color'),
        ('content', '0002_auto_20200413_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Program'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Program'),
        ),
    ]
