# Generated by Django 3.0.10 on 2020-10-22 14:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201002_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpage',
            name='featured_copy',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Featured content copy', null=True),
        ),
    ]
