version: '3.7'

services:
  web:
    build: ./app
    image: vs-python
    command: python /app/manage.py runserver 0:8080
    volumes:
      - ./app:/app:cached
      - ./docker-data/media:/media:cached
      - ./docker-data/django-static:/static:cached
    # - ./app:/app
    # - ./docker-data/media:/media
    # - ./docker-data/django-static:/static
    # ports:
    # - "8000:8080"
    env_file:
    - ./docker-data/secret.env
    # depends_on:
    # - db

  nginx:
    build: ./nginx
    ports:
    # - "8888:80"
    # - "8888:8888"
    - "80:8888"
    depends_on:
    - web
    volumes:
    - ./docker-data/media:/media
