# Generated by Django 3.0.5 on 2020-04-03 20:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='images/lessons/')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('intro_copy', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Marketing Copy')),
                ('student_intro', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Copy for the Student Page')),
                ('teachers_guide', models.URLField(blank=True, null=True)),
                ('learning_outcomes', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('audience', models.ManyToManyField(blank=True, to='taxonomy.Audience')),
                ('program', models.ManyToManyField(blank=True, to='taxonomy.Program')),
                ('standards_alignment', models.ManyToManyField(blank=True, to='taxonomy.Standard')),
                ('tag', models.ManyToManyField(blank=True, to='taxonomy.Tag')),
                ('time_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.TimeEstimate')),
                ('topic', models.ManyToManyField(blank=True, to='taxonomy.Topic')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'managed': True,
            },
        ),
    ]
