# Generated by Django 3.0.5 on 2020-04-07 18:00

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonaudiencerelationship',
            name='lesson',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_relationship', to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessonstandardsrelationship',
            name='lesson',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_relationship', to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessontagrelationship',
            name='lesson',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relationship', to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='lessontopicrelationship',
            name='lesson',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationship', to='lessons.Lesson'),
        ),
    ]
