# Generated by Django 3.0.6 on 2020-05-28 21:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('overview_copy', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('student_copy', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('teachers_desc', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Text to display', required=True))])), ('copy', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('asset', wagtail.snippets.blocks.SnippetChooserBlock('assets.Asset')), ('activity', wagtail.snippets.blocks.SnippetChooserBlock('activity.Activity')), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('external', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='Asset can be accessed here.', max_length=50)), ('url', wagtail.core.blocks.URLBlock(help_text='Link to external resource', required=True))])), ('google_doc', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to Google Doc', required=True))])), ('codap', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to CODAP', required=True))])), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True)),
                ('students_desc', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Text to display', required=True))])), ('copy', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('asset', wagtail.snippets.blocks.SnippetChooserBlock('assets.Asset')), ('activity', wagtail.snippets.blocks.SnippetChooserBlock('activity.Activity')), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('external', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='Asset can be accessed here.', max_length=50)), ('url', wagtail.core.blocks.URLBlock(help_text='Link to external resource', required=True))])), ('google_doc', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to Google Doc', required=True))])), ('codap', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to CODAP', required=True))])), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.ActivityType')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Audience')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Program')),
                ('time_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.TimeEstimate')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Topic')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityTopicRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationship', to='activity.Activity')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTagRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relationship', to='activity.Activity')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStandardsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_relationship', to='activity.Activity')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAudienceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_relationship', to='activity.Activity')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Audience')),
            ],
        ),
    ]
