# Generated by Django 3.0.5 on 2020-04-06 11:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='link_to_activity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tag',
        ),
        migrations.AddField(
            model_name='activity',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='internal_link',
            field=models.ForeignKey(blank=True, help_text='Select an internal Wagtail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='overview_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='student_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityTagRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tag_relationship', to='activity.Activity')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Tag')),
            ],
        ),
    ]
