# Generated by Django 3.0.5 on 2020-04-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time_estimate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='topic',
        ),
    ]
