# Generated by Django 3.0.10 on 2020-10-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20201022_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True, 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
