# Generated by Django 3.0.5 on 2020-04-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20200406_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tag',
        ),
    ]
