# Generated by Django 3.0.5 on 2020-04-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_remove_activity_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='teachers_guide',
        ),
    ]
