# Generated by Django 3.0.5 on 2020-05-01 16:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_program_program_color'),
        ('activity', '0009_remove_activity_teachers_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytagrelationship',
            name='activity',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relationship', to='activity.Activity'),
        ),
        migrations.CreateModel(
            name='ActivityTopicRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationship', to='activity.Activity')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStandardsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_relationship', to='activity.Activity')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAudienceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_relationship', to='activity.Activity')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Audience')),
            ],
        ),
    ]
