# Generated by Django 3.0.5 on 2020-05-01 17:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20200501_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='internal_link',
        ),
        migrations.AddField(
            model_name='activity',
            name='students_desc',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Text to display', required=True))])), ('copy', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('asset', wagtail.snippets.blocks.SnippetChooserBlock('assets.Asset')), ('activity', wagtail.snippets.blocks.SnippetChooserBlock('activity.Activity')), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('external', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='Asset can be accessed here.', max_length=50)), ('url', wagtail.core.blocks.URLBlock(help_text='Link to external resource', required=True))])), ('google_doc', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to Google Doc', required=True))])), ('codap', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to CODAP', required=True))])), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='teachers_desc',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Text to display', required=True))])), ('copy', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('asset', wagtail.snippets.blocks.SnippetChooserBlock('assets.Asset')), ('activity', wagtail.snippets.blocks.SnippetChooserBlock('activity.Activity')), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('external', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='Asset can be accessed here.', max_length=50)), ('url', wagtail.core.blocks.URLBlock(help_text='Link to external resource', required=True))])), ('google_doc', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to Google Doc', required=True))])), ('codap', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to CODAP', required=True))])), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
