# Generated by Django 3.0.4 on 2020-04-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20200402_1821'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='audience',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Audience'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='program',
        ),
        migrations.AddField(
            model_name='lesson',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Program'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='standards_alignment',
        ),
        migrations.AddField(
            model_name='lesson',
            name='standards_alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Standard'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='tag',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Tag'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Topic'),
        ),
    ]
