# Generated by Django 3.0.4 on 2020-04-02 20:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20200402_1821'),
        ('lessons', '0003_auto_20200402_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='standards_alignment',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='tag',
        ),
        migrations.CreateModel(
            name='LessonStandardsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_standards_relationship', to='lessons.Lesson')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='LessonAudienceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Audience')),
                ('lesson', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_audience_relationship', to='lessons.Lesson')),
            ],
        ),
    ]
