apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjAgKGxpbnV4KSIKCX0sCgkiY3JlZHNTdG9yZSI6ICJwYXNzIgp9
kind: Secret
metadata:
  creationTimestamp: "2019-08-05T16:07:35Z"
  name: regcred
  namespace: default
  resourceVersion: "2281027"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: 235ca033-b79b-11e9-8f39-d6ff0a0e36f1
type: kubernetes.io/dockerconfigjson