apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlozSmxZWFIzYUdsMFpXRndaVHBKYkRKdFlrcG1ZaUU9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xMSAobGludXgpIgoJfQp9
kind: Secret
metadata:
  name: regcred
  namespace: curriculum
type: kubernetes.io/dockerconfigjson
