# Generated by Django 3.0.4 on 2020-04-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_text', models.CharField(blank=True, help_text='Marketing-speak about GRMI EDU (100 Characters Max)', max_length=100, null=True)),
                ('featured_title', models.CharField(blank=True, help_text='Section title', max_length=100, null=True)),
                ('featured_copy', models.TextField(blank=True, help_text='Featured content copy', null=True)),
                ('feature1_title', models.CharField(blank=True, help_text='LabVenture Block 1', max_length=50, null=True)),
                ('feature1_copy', models.TextField(blank=True, help_text='Short copy blurb', null=True)),
                ('feature2_title', models.CharField(blank=True, help_text='LabVenture Block 2', max_length=50, null=True)),
                ('feature2_copy', models.TextField(blank=True, help_text='Short copy blurb', null=True)),
                ('feature3_title', models.CharField(blank=True, help_text='LabVenture Block 3', max_length=50, null=True)),
                ('feature3_copy', models.TextField(blank=True, help_text='Short copy blurb', null=True)),
                ('feature4_title', models.CharField(blank=True, help_text='LabVenture Block 4', max_length=50, null=True)),
                ('feature4_copy', models.TextField(blank=True, help_text='Short copy blurb', null=True)),
                ('feature5_title', models.CharField(blank=True, help_text='LabVenture Block 5', max_length=50, null=True)),
                ('feature5_copy', models.TextField(blank=True, help_text='Short copy blurb', null=True)),
                ('feature6_title', models.CharField(blank=True, help_text='LabVenture Block 6', max_length=50, null=True)),
                ('feature6_copy', models.TextField(blank=True, help_text='Short copy blurb', null=True)),
                ('labventure_section_title', models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True)),
                ('labventure_section_copy', models.TextField(blank=True, help_text='Marketing copy for the Labventure.', max_length=255, null=True)),
                ('labventure_section_button_text', models.CharField(blank=True, help_text='Text for call to action button (25 Characters Max).', max_length=25, null=True)),
                ('labventure_section_button_link', models.URLField(blank=True, help_text='Link that call to button action links to', null=True)),
                ('vitalsigns_section_title', models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True)),
                ('vitalsigns_section_copy', models.TextField(blank=True, help_text='Marketing copy for the Vital Signs.', null=True)),
                ('vitalsigns_section_button_text', models.CharField(blank=True, help_text='Text for call to action button (25 Characters Max).', max_length=25, null=True)),
                ('vitalsigns_section_button_link', models.URLField(blank=True, help_text='Link that call to button action links to', null=True)),
                ('gmri_section_title', models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True)),
                ('gmri_section_copy', models.TextField(blank=True, help_text='Marketing copy for the GMRI.', null=True)),
                ('c2a_1_section_title', models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True)),
                ('c2a_1_section_copy', models.CharField(blank=True, help_text='Marketing copy (255 Characters Max - Optional).', max_length=255, null=True)),
                ('c2a_1_section_button_text', models.CharField(blank=True, help_text='Text for call to action button (25 Characters Max).', max_length=25, null=True)),
                ('c2a_1_section_button_link', models.URLField(blank=True, help_text='Link that call to button action links to', null=True)),
                ('c2a_2_section_title', models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True)),
                ('c2a_2_section_copy', models.CharField(blank=True, help_text='Marketing copy (255 Characters Max - Optional).', max_length=255, null=True)),
                ('c2a_2_section_button_text', models.CharField(blank=True, help_text='Text for call to action button (25 Characters Max).', max_length=25, null=True)),
                ('c2a_2_section_button_link', models.URLField(blank=True, help_text='Link that call to button action links to', null=True)),
                ('c2a_3_section_title', models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True)),
                ('c2a_3_section_copy', models.CharField(blank=True, help_text='Marketing copy (255 Characters Max - Optional).', max_length=255, null=True)),
                ('c2a_3_section_button_text', models.CharField(blank=True, help_text='Text for call to action button (25 Characters Max).', max_length=25, null=True)),
                ('c2a_3_section_button_link', models.URLField(blank=True, help_text='Link that call to button action links to', null=True)),
                ('feature1_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('feature1_link', models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('feature2_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('feature2_link', models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('feature3_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('feature3_link', models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('feature4_link', models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('feature5_link', models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('feature6_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('feature6_link', models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('gmri_section_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('gmri_section_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('image', models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('labventure_section_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('labventure_section_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('vitalsigns_section_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('vitalsigns_section_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
