# Generated by Django 3.0.5 on 2020-04-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='topic',
        ),
        migrations.AddField(
            model_name='asset',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='internal_link',
            field=models.ForeignKey(blank=True, help_text='Select an internal Wagtail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
