# Generated by Django 3.0.8 on 2020-08-07 15:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_link',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('external', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='Asset can be accessed here.', max_length=50)), ('url', wagtail.core.blocks.URLBlock(help_text='Link to external resource', required=True))])), ('google_doc', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to Google Doc', required=True))])), ('codap', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock(help_text='Link to CODAP', required=True))])), ('video', wagtail.core.blocks.StructBlock([('youtube_video', wagtail.core.blocks.CharBlock(help_text='YouTube Video ID (https://youtu.be/XXX-XXX the XXX-XXX section)', required=True))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
