# Generated by Django 3.0.5 on 2020-04-27 17:34

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200427_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='embed_tag',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='student_intro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Copy for the Student Page'),
        ),
    ]
