# Generated by Django 3.0.10 on 2020-11-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('assets', '0004_auto_20200807_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.Program'),
        ),
    ]
