# Generated by Django 3.0.5 on 2020-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200427_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='embed_tag',
            field=models.TextField(blank=True),
        ),
    ]
