# Generated by Django 3.0.5 on 2020-04-28 18:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200428_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='embed_tag',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='internal_link',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_link',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('external', wagtail.core.blocks.URLBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock())], blank=True, null=True),
        ),
    ]
