# Generated by Django 3.0.5 on 2020-04-28 19:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20200428_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_link',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('external', wagtail.core.blocks.URLBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
