# Generated by Django 3.0.5 on 2020-05-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200428_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettagrelationship',
            old_name='module',
            new_name='asset',
        ),
    ]
