# Generated by Django 3.0.4 on 2020-04-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('teachers_guide', models.URLField(blank=True, null=True)),
                ('overview_copy', models.TextField(blank=True, null=True)),
                ('student_copy', models.TextField(blank=True, null=True)),
                ('audience', models.ManyToManyField(blank=True, to='taxonomy.Audience')),
                ('program', models.ManyToManyField(blank=True, to='taxonomy.Program')),
                ('tag', models.ManyToManyField(blank=True, to='taxonomy.Tag')),
                ('time_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.TimeEstimate')),
                ('topic', models.ManyToManyField(blank=True, to='taxonomy.Topic')),
            ],
            options={
                'verbose_name': 'Take Action Activity',
                'verbose_name_plural': 'Take Action Activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MiniLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('display_title', models.CharField(blank=True, max_length=100)),
                ('teachers_guide', models.URLField(blank=True, null=True)),
                ('overview_copy', models.TextField(blank=True, null=True)),
                ('student_copy', models.TextField(blank=True, null=True)),
                ('audience', models.ManyToManyField(blank=True, to='taxonomy.Audience')),
                ('program', models.ManyToManyField(blank=True, to='taxonomy.Program')),
                ('tag', models.ManyToManyField(blank=True, to='taxonomy.Tag')),
                ('time_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.TimeEstimate')),
                ('topic', models.ManyToManyField(blank=True, to='taxonomy.Topic')),
            ],
            options={
                'verbose_name': 'Mini-Lesson',
                'verbose_name_plural': 'Mini-Lessons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GuidedReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('teachers_guide', models.URLField()),
                ('overview_copy', models.TextField(blank=True, null=True)),
                ('student_copy', models.TextField(blank=True, null=True)),
                ('audience', models.ManyToManyField(blank=True, to='taxonomy.Audience')),
                ('program', models.ManyToManyField(blank=True, to='taxonomy.Program')),
                ('tag', models.ManyToManyField(blank=True, to='taxonomy.Tag')),
                ('time_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.TimeEstimate')),
                ('topic', models.ManyToManyField(blank=True, to='taxonomy.Topic')),
            ],
            options={
                'verbose_name': 'Guided Reading',
                'verbose_name_plural': 'Guided Reading',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('teachers_guide', models.URLField(blank=True, null=True)),
                ('overview_copy', models.TextField(blank=True, null=True)),
                ('student_copy', models.TextField(blank=True, null=True)),
                ('audience', models.ManyToManyField(blank=True, to='taxonomy.Audience')),
                ('program', models.ManyToManyField(blank=True, to='taxonomy.Program')),
                ('tag', models.ManyToManyField(blank=True, to='taxonomy.Tag')),
                ('time_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.TimeEstimate')),
                ('topic', models.ManyToManyField(blank=True, to='taxonomy.Topic')),
            ],
        ),
    ]
