# Generated by Django 3.0.4 on 2020-04-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True, 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
