# Generated by Django 3.0.5 on 2020-04-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('lessons', '0001_initial'),
        ('activity', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='feature1_link',
            field=models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature2_link',
            field=models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature3_link',
            field=models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature4_link',
            field=models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature5_link',
            field=models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature6_link',
            field=models.ForeignKey(blank=True, help_text='Link to resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.Lesson'),
        ),
    ]
