# Generated by Django 3.0.10 on 2020-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200731_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature1_image_alt',
            field=models.CharField(blank=True, help_text='Alt-tag for image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature2_image_alt',
            field=models.CharField(blank=True, help_text='Alt-tag for image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature3_image_alt',
            field=models.CharField(blank=True, help_text='Alt-tag for image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature6_image_alt',
            field=models.CharField(blank=True, help_text='Alt-tag for image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gmri_section_hero_alt',
            field=models.CharField(blank=True, help_text='Alt-tag for image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='labventure_section_hero_alt',
            field=models.CharField(blank=True, help_text='Alt-tag for image', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vitalsigns_section_hero_alt',
            field=models.CharField(blank=True, help_text='Alt-tag for image', max_length=100, null=True),
        ),
    ]
