# Generated by Django 3.0.5 on 2020-04-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200406_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='c2a_1_section_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this box.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='c2a_2_section_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this box.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='c2a_3_section_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this box.'),
        ),
    ]
