# Generated by Django 3.0.10 on 2020-11-13 23:12

import activity.models
import assets.models
from django.db import migrations
import modules.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201104_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_items',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Block Title', required=True)), ('copy', wagtail.core.blocks.CharBlock(help_text='Quote Text', required=True))])), ('module', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Block Title', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Featured Block Image', required=True)), ('copy', wagtail.core.blocks.CharBlock(help_text='Module Description', required=True)), ('module', wagtail.snippets.blocks.SnippetChooserBlock(modules.models.Module, help_text='Select Module to link to', required=True))])), ('activity', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Block Title', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Featured Block Image', required=True)), ('copy', wagtail.core.blocks.CharBlock(help_text='Activity Description', required=True)), ('activity', wagtail.snippets.blocks.SnippetChooserBlock(activity.models.Activity, help_text='Select Activity to link to', required=True))])), ('asset', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Block Title', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Featured Block Image', required=True)), ('copy', wagtail.core.blocks.CharBlock(help_text='Asset Description', required=True)), ('asset', wagtail.snippets.blocks.SnippetChooserBlock(assets.models.Asset, help_text='Select Asset to link to', required=True))]))], blank=True, null=True, verbose_name='Lessons Tab Content'),
        ),
    ]
