# Generated by Django 3.0.5 on 2020-04-07 18:00

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleaudiencerelationship',
            name='module',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_relationship', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='modulestandardsrelationship',
            name='module',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_relationship', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='moduletagrelationship',
            name='module',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relationship', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='moduletopicrelationship',
            name='module',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationship', to='modules.Module'),
        ),
    ]
