# Generated by Django 3.0.6 on 2020-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='live',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
    ]
