# Generated by Django 3.0.4 on 2020-04-02 20:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20200402_1821'),
        ('modules', '0002_auto_20200402_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lessons_desc',
        ),
        migrations.RemoveField(
            model_name='module',
            name='standards_alignment',
        ),
        migrations.RemoveField(
            model_name='module',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='module',
            name='topic',
        ),
        migrations.AddField(
            model_name='module',
            name='module_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Friendly Description of Module'),
        ),
        migrations.CreateModel(
            name='ModuleTopicRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_topic_relationship', to='modules.Module')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleTagRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_tag_relationship', to='modules.Module')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleStandardsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_standards_relationship', to='modules.Module')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAudienceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.Audience')),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_audience_relationship', to='modules.Module')),
            ],
        ),
    ]
