# Generated by Django 3.0.5 on 2020-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20200407_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_download',
            field=models.URLField(blank=True, null=True),
        ),
    ]
