# Generated by Django 3.0.5 on 2020-04-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
