# Generated by Django 3.0.4 on 2020-04-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'managed': True, 'verbose_name': 'Type of Activity', 'verbose_name_plural': 'Type of Activities'},
        ),
    ]
